### ISSUE TITLE
EIPW should warn if an otherwise valid EIP file is contained in a folder not named `EIPS`

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#61]
See https://github.com/ethereum/EIPs/issues/6172#issuecomment-1364709916

**Comment by SamWilsn** [comment]
The GitHub Action for `eipw` only checks files in the `EIPS` directory (because of the template, markdown in asset folders, etc.) You're suggesting that `eipw` should check all `eip-*.md` files regardless of where they are, be silent if they don't pass validation, but warn if they pass validation but aren't in `EIPS/`?

**Comment by Pandapip1** [comment]
> You're suggesting that `eipw` should check all `eip-*.md` files regardless of where they are, be silent if they don't pass validation, but warn if they pass validation but aren't in `EIPS/`?

Yes, that's exactly what I'm suggesting.

**Comment by Pandapip1** [comment]
Will be implemented in the review bot instead.
